server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: your_mysql_user
    password: your_mysql_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
